---
name: Tie-Hash-Regex
version: 1.02
author:
  - 'Dave Cross <dave@mag-sol.com>'
abstract: Match hash keys using Regular Expressions
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Attribute::Handlers: 0
  Tie::Hash: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Tie::Hash::Regex:
    file: lib/Tie/Hash/Regex.pm
    version: 15
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
