# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-Hash-Regex
version:      1.00
version_from: Regex.pm
installdirs:  site
requires:
    Attribute::Handlers:           0.76
    Test::Pod:                     0
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
